# Generated by Django 4.0.1 on 2022-01-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=50)),
                ('Name', models.CharField(max_length=155)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Product_Name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('Price', models.CharField(max_length=199)),
                ('Address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.TextField()),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
