# Generated by Django 4.0 on 2022-01-03 19:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearniMaterials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Document_name', models.CharField(max_length=100)),
                ('Course_name', models.CharField(max_length=100)),
                ('Year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('Semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('Document', models.FileField(upload_to='documents')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('vid_description', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
