# Generated by Django 4.0 on 2022-01-03 19:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('Software_description', models.CharField(max_length=200)),
                ('Software_file', models.FileField(upload_to='softwares')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
