# Generated by Django 4.0.1 on 2022-01-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomatic', '0002_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
